#!/bin/sh
# Undo the 2026-09-19 archive run. Reverses order, safe to rerun.
set -x
gh repo unarchive realdubb/.tmux --yes && gh repo edit realdubb/.tmux --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/audio-guestbook --yes && gh repo edit realdubb/audio-guestbook --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/ts-test --yes && gh repo edit realdubb/ts-test --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/interactive-coding-challenges --yes && gh repo edit realdubb/interactive-coding-challenges --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/blog --yes && gh repo edit realdubb/blog --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/electron-react-boilerplate --yes && gh repo edit realdubb/electron-react-boilerplate --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/github-tools-vsts --yes && gh repo edit realdubb/github-tools-vsts --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/docker-elk --yes && gh repo edit realdubb/docker-elk --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/graphql --yes && gh repo edit realdubb/graphql --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/signature_pad --yes && gh repo edit realdubb/signature_pad --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/k8s-by-component --yes && gh repo edit realdubb/k8s-by-component --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/react-stepzilla --yes && gh repo edit realdubb/react-stepzilla --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/my-app-boilerplate --yes && gh repo edit realdubb/my-app-boilerplate --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/login-flow --yes && gh repo edit realdubb/login-flow --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/feathers-starter-react-redux-login-roles --yes && gh repo edit realdubb/feathers-starter-react-redux-login-roles --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/env --yes && gh repo edit realdubb/env --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/airport-explorer-source --yes && gh repo edit realdubb/airport-explorer-source --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/SwiftCheatsheet --yes && gh repo edit realdubb/SwiftCheatsheet --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/js-file-download --yes && gh repo edit realdubb/js-file-download --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/public --yes && gh repo edit realdubb/public --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/hotel --yes && gh repo edit realdubb/hotel --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/tribeca --yes && gh repo edit realdubb/tribeca --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/digital_video_introduction --yes && gh repo edit realdubb/digital_video_introduction --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/menu_monkey --yes && gh repo edit realdubb/menu_monkey --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/catch-of-the-day --yes && gh repo edit realdubb/catch-of-the-day --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/scratch --yes && gh repo edit realdubb/scratch --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/6310 --yes && gh repo edit realdubb/6310 --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/name-contests --yes && gh repo edit realdubb/name-contests --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/ember-bank --yes && gh repo edit realdubb/ember-bank --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/product-app --yes && gh repo edit realdubb/product-app --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/react-native-redux-groceries --yes && gh repo edit realdubb/react-native-redux-groceries --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/sunshine-app --yes && gh repo edit realdubb/sunshine-app --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/MiniKeePass --yes && gh repo edit realdubb/MiniKeePass --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/local-npm --yes && gh repo edit realdubb/local-npm --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/synology-cast-photos --yes && gh repo edit realdubb/synology-cast-photos --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/react-firebase-crud --yes && gh repo edit realdubb/react-firebase-crud --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/snowflake-hapi-openshift --yes && gh repo edit realdubb/snowflake-hapi-openshift --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/cs193p-Spring-2016 --yes && gh repo edit realdubb/cs193p-Spring-2016 --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/synology-cast-photos-android --yes && gh repo edit realdubb/synology-cast-photos-android --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/ElectroCRUD --yes && gh repo edit realdubb/ElectroCRUD --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/rspec-best-practices --yes && gh repo edit realdubb/rspec-best-practices --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/Materials-CS193A-Android-App-Development-Standford --yes && gh repo edit realdubb/Materials-CS193A-Android-App-Development-Standford --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/hkids-app --yes && gh repo edit realdubb/hkids-app --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/angular2-tv-tracker --yes && gh repo edit realdubb/angular2-tv-tracker --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/spartify --yes && gh repo edit realdubb/spartify --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/blackboard-binder --yes && gh repo edit realdubb/blackboard-binder --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/youtubeplayer --yes && gh repo edit realdubb/youtubeplayer --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/sudoku --yes && gh repo edit realdubb/sudoku --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/engineering-app --yes && gh repo edit realdubb/engineering-app --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/bookclub --yes && gh repo edit realdubb/bookclub --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/Searching-array-for-character-C-Program --yes && gh repo edit realdubb/Searching-array-for-character-C-Program --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/tab-resize --yes && gh repo edit realdubb/tab-resize --remove-topic jev-archived-2026-09
gh repo unarchive realdubb/realdubb.github.io --yes && gh repo edit realdubb/realdubb.github.io --remove-topic jev-archived-2026-09
